{-
Problem 2 - Project Euler

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.



http://projecteuler.net/index.php?section=problems&id=2
-}

fib = 0:1:zipWith (+) fib (tail fib)
fibevensum x = sum . filter even . takeWhile (< x) $ fib

{-
    fibevensum = fibevensum' fib
fibevensum' (x:xs) thr
    | x > thr   = 0
    | otherwise = if even x then x + fibevensum' xs thr else fibevensum' xs thr
-}
problem002 = fibevensum 4000000

main = do
    print $ "problem002: answer " ++ show problem002
