[package]
name = "project-euler"
version = "0.1.0"
authors = ["emergent <yosikawa@gmail.com>"]
edition = "2021"

[dependencies]
num = "*"
itertools = "*"
num-integer = "0.1.45"
num-traits = "0.2.15"
num-derive = "0.3.3"
num-iter = "0.1.43"
