#! /usr/bin/env python3
'''
Problem 29 - Project Euler


Consider all integer combinations of <i>a</i><sup><i>b</i></sup> for 2 <= <i>a</i> <= 5 and 2 <= <i>b</i> <= 5:

<blockquote>2<sup>2</sup>=4, 2<sup>3</sup>=8, 2<sup>4</sup>=16, 2<sup>5</sup>=32<br>
3<sup>2</sup>=9, 3<sup>3</sup>=27, 3<sup>4</sup>=81, 3<sup>5</sup>=243<br>
4<sup>2</sup>=16, 4<sup>3</sup>=64, 4<sup>4</sup>=256, 4<sup>5</sup>=1024<br>
5<sup>2</sup>=25, 5<sup>3</sup>=125, 5<sup>4</sup>=625, 5<sup>5</sup>=3125<br>
</blockquote>
If they are then placed in numerical order, with any repeats removed, we get the following sequence of 15 distinct terms:

4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125

How many distinct terms are in the sequence generated by <i>a</i><sup><i>b</i></sup> for 2 <= <i>a</i> <= 100 and 2 <= <i>b</i> <= 100?



http://projecteuler.net/index.php?section=problems&id=029
'''

if __name__ == '__main__':
    ans = len(set([a ** b for a in range(2, 101) for b in range(2, 101)]))
    print(ans)
