#! /usr/bin/env boot
; Problem 2 - Project Euler
;
; Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
;   1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
; By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
; 
; http://projecteuler.net/index.php?section=problems&id=2

(defn fibmax' [x xs]
  (let [n (+ (first xs) (second xs))]
    (if (< x n)
      xs
      (fibmax' x (cons n xs)))))

(defn fibmax [x]
  (cond
    (= x 1) '(1)
    (= x 2) '(1 2)
    :else (reverse (fibmax' x '(2 1)))))

(defn fibevensum [x]
  (reduce + (filter even? (fibmax x))))

(defn -main []
  (println (fibevensum 4000000)))
